end_msg_main = "YOU ARE DEAD"
end_msg[0] = "Really?";
end_msg[1] = "You look pretty dead to me...";
end_msg[2] = "Cool, cool...";
end_msg[3] = "Th... That's it?";
end_msg[4] = "Again.";
end_msg[5] = "Great, just great.";
cur_msg = choose(end_msg[0],end_msg[1],end_msg[2],end_msg[3],end_msg[4],end_msg[5]);
menu_sel = 0;
menu_text[0] = "Try Again?";
menu_text[1] = "Bid farewell.";
text_y = 200;
text_x = 160;